tailwind.config = {
    content: ["./src/**/*.{html,ts,scss}"],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "secondary-container": "var(--color-secondary-container)",
                "on-primary": "var(--color-on-primary)",
                "outline": "var(--color-outline)",
                "error-container": "var(--color-error-container)",
                "surface-tint": "var(--color-surface-tint)",
                "on-secondary-fixed": "var(--color-on-secondary-fixed)",
                "surface-container-lowest": "var(--color-surface-container-lowest)",
                "on-primary-fixed": "var(--color-on-primary-fixed)",
                "tertiary": "var(--color-tertiary)",
                "secondary": "var(--color-secondary)",
                "primary-container": "var(--color-primary-container)",
                "on-surface": "var(--color-on-surface)",
                "background": "var(--color-background)",
                "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
                "on-error-container": "var(--color-on-error-container)",
                "on-secondary-container": "var(--color-on-secondary-container)",
                "error": "var(--color-error)",
                "inverse-surface": "var(--color-inverse-surface)",
                "on-surface-variant": "var(--color-on-surface-variant)",
                "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
                "on-error": "var(--color-on-error)",
                "surface-dim": "var(--color-surface-dim)",
                "surface-container": "var(--color-surface-container)",
                "on-secondary": "var(--color-on-secondary)",
                "primary-fixed-dim": "var(--color-primary-fixed-dim)",
                "tertiary-fixed": "var(--color-tertiary-fixed)",
                "outline-variant": "var(--color-outline-variant)",
                "surface-container-low": "var(--color-surface-container-low)",
                "on-tertiary-container": "var(--color-on-tertiary-container)",
                "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
                "secondary-fixed": "var(--color-secondary-fixed)",
                "primary-fixed": "var(--color-primary-fixed)",
                "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
                "inverse-primary": "var(--color-inverse-primary)",
                "tertiary-container": "var(--color-tertiary-container)",
                "surface-variant": "var(--color-surface-variant)",
                "primary": "var(--color-primary)",
                "on-background": "var(--color-on-background)",
                "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
                "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
                "inverse-on-surface": "var(--color-inverse-on-surface)",
                "on-tertiary": "var(--color-on-tertiary)",
                "on-primary-container": "var(--color-on-primary-container)",
                "surface-bright": "var(--color-surface-bright)",
                "surface-container-highest": "var(--color-surface-container-highest)",
                "surface": "var(--color-surface)",
                "surface-container-high": "var(--color-surface-container-high)"
            },
            fontFamily: {
                "headline": ["Manrope"],
                "body": ["Manrope"],
                "label": ["Manrope"]
            },
            borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
        },
    },
}